WIP: Add VM create client
oVirt/go-ovirt-client pull request #1
Opened 2021-06-23 15:30 UTC by Gal-Zaidman

This change:
- adds the oVirt VM create client
- add list hosts by cluster
- changes CPU topology to int64 so we can use it with oVirt API
- adds VMInitialization struct
- adds errors package

** This is still very much a work in progress

2021-06-23 18:44 UTC, janoszen commented
Hey @Gal-Zaidman can this wait until next week or do you need it urgently?

2021-06-24 05:56 UTC, Gal-Zaidman commented
> Hey @Gal-Zaidman can this wait until next week or do you need it urgently?

Hi, this is really not urget just posted what I started so it will be available.... get back to your PTO and have fun :D

2021-06-28 08:34 UTC, janoszen requested changes

2021-06-28 08:34 UTC, janoszen commented on client_vm_create.go
> +	preCreateConfigurations() error
It seems to me that these functions should be executed in order, and only in order. It would be better to create separate functions and then chain them as below. The current solution is too easy to break from the caller side.

```go
steps := map[string]func() err{"step1": func1, "step2":func2, "step3":func3}
for stepName, step := range steps; {
    if err := step(); err != nil {
        return fmt.Errorf("step %s in VM creation failed (%w)", stepName, err);
    }
}
```

You can save state between steps by passing a receiver function:

```go
type vmCreationStepsState struct {
}

func (v *vmCreationStepsState) step1() error {
}

//...
state := &vmCreationStepsState{}
steps := map[string]func() err{"step1": state.func1}
```

2021-06-28 08:34 UTC, janoszen commented on client_vm_create.go
> +	switch policy {
It seems to me that we should only allow correct values here and fail if an invalid value is provided. Also, we should create consts for the enum values instead of hardcoding them as strings.

2021-07-18 06:55 UTC, Gal-Zaidman commented
@janosdebugs after our chat today you are going to continue this effort, so feel free to close take the changes and close the PR

2021-07-18 08:55 UTC, janosdebugs commented
Thanks @Gal-Zaidman I'll take over from here.

2021-07-18 11:17 UTC, closed without merging