introduce VM Initialization Support
oVirt/go-ovirt-client pull request #104
Opened 2021-12-14 14:51 UTC by eslutsky

Signed-off-by: Evgeny Slutsky <eslutsky@redhat.com>

## Please describe the change you are making

2021-12-14 18:34 UTC, janosdebugs commented
This PR should be rebased onto #103 as it contains a refactor for `convertSDKVM`.

2021-12-15 12:15 UTC, eslutsky commented
> This PR should be rebased onto #103 as it contains a refactor for `convertSDKVM`.

rebase is done

2021-12-15 13:44 UTC, janosdebugs requested changes
A few changes are needed. I think we need to decide if we want the initialization parameters to be a separate object. If yes then they need a proper builder, if no then we need to add individual functions to set those parameters on the VM itself. Currently, the initialization is a struct and is not exported, whereas it would need an interface to work properly.

2021-12-15 13:44 UTC, janosdebugs commented on client_vm.go
> +	Initialization() *initialization
`initialization` is a non-exported struct. Returning this from an exported function is going to lead to issues.

2021-12-15 13:44 UTC, janosdebugs commented on client_vm.go
> +func newInitialization() *initialization {
Why is this not exported?

2021-12-15 13:44 UTC, janosdebugs commented on client_vm.go
> +	initialization *initialization
We should use interface types here, not structs.

2021-12-15 13:44 UTC, janosdebugs commented on client_vm.go
> +	MustWithInitialization(initialization initialization) BuildableVMParameters
This will not work because initialization is not exported and isn't tested either. Please make a proper interface for initialization.

2021-12-16 15:20 UTC, eslutsky commented on client_vm.go
> +	Initialization() *initialization
done

2021-12-16 15:21 UTC, eslutsky commented on client_vm.go
> +func newInitialization() *initialization {
done

2021-12-16 15:21 UTC, eslutsky commented on client_vm.go
> +	initialization *initialization
done

2021-12-16 15:21 UTC, eslutsky commented on client_vm.go
> +	MustWithInitialization(initialization initialization) BuildableVMParameters
done

2021-12-16 16:05 UTC, janosdebugs requested changes
A few things are still not right after the refactor. Please also check the linting.

2021-12-16 16:05 UTC, janosdebugs commented on client_vm.go
> +		init.WithCustomScript(customScript)
It is not necessary to use the With functions here since you are directly accessing the struct here.

2021-12-16 16:05 UTC, janosdebugs commented on client_vm_create.go
> +		if init.customScript != "" {
This seems to be broken after the refactor, see the linting errors.

2021-12-19 15:12 UTC, eslutsky commented on client_vm.go
> +		init.WithCustomScript(customScript)
done

2021-12-19 15:12 UTC, eslutsky commented on client_vm.go
> +	WithCustomScript(customScript string) Initialization
done

2021-12-19 15:12 UTC, eslutsky commented on client_vm_create.go
> +		if init.customScript != "" {
fixed

2022-01-03 17:39 UTC, janosdebugs approved these changes

2022-01-03 17:39 UTC, janosdebugs commented
@eslutsky looks good, feel free to merge if tested against an oVirt engine.

2022-01-04 12:44 UTC, merged