add check that vnic with same name doesn't has the same network
oVirt/go-ovirt-client pull request #109
Opened 2022-02-03 13:19 UTC by mgold1234

## Please describe the change you are making

This PR fixes #82 and check that vnic doesn't has same network

## Are you the owner of the code you are sending in, or do you have permission of the owner?

yes

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

yes

2022-02-03 13:22 UTC, janosdebugs requested changes
Hey @mgold1234 thank you for your continued work on this. Can I ask you to add tests for both positive and negative for this case? It would be useful to verify the behavior against the real oVirt engine as well as the mock facility.

2022-02-09 13:54 UTC, mgold1234 commented
> Hey @mgold1234 thank you for your continued work on this. Can I ask you to add tests for both positive and negative for this case? It would be useful to verify the behavior against the real oVirt engine as well as the mock facility.

hi @janosdebugs, I added test that check different network (if there is exist one, else check the same network)  and same name

2022-02-09 16:40 UTC, janosdebugs requested changes
Hey @mgold1234 thank you so much for working on this. I know this is a tricky issue, I commented on a few corner cases that we may want to check on. Could you try and get those covered too? Thank you.

2022-02-09 16:40 UTC, janosdebugs commented on client_nic_test.go
> +func assertCannotCreateNICWithSameNameDiffNetwork(
I would suggest renaming this to `assertCannotCreateNICWithVNICProfile` since that more accurately covers what this function does and makes the function reusable.

2022-02-09 16:40 UTC, janosdebugs commented on client_nic_test.go
> +		t.Fatalf("create 2 NICs with same name %s", name)
Please also change this message.

2022-02-09 16:40 UTC, janosdebugs commented on client_nic_test.go
> +	if nic != nil {
It is preferable from a readability perspective to check the error, not the returned object.

2022-02-09 16:40 UTC, janosdebugs commented on client_nic_test.go
> +func assertCannotCreateNICWithSameName(
This name change is misleading. The error message below should also be changed.

2022-02-09 16:40 UTC, janosdebugs commented on client_nic_create_test.go
> +	DiffVNICProfile, _ := assertCanFindDiffVNICProfile(helper, helper.GetVNICProfileID())
What happens if there is no second vnic profile? We cannot assume there is a secondary profile available. Can we create a second profile? What if the secondary profile is on the same network as the primary? Does it still work?

2022-02-09 16:54 UTC, mgold1234 commented on client_nic_test.go
> +func assertCannotCreateNICWithSameNameDiffNetwork(
WDYT about assertCannotCreateNICWithSameVNICProfile? 
it is not clear just with vnic profile.

2022-02-09 16:56 UTC, mgold1234 commented on client_nic_test.go
> +		t.Fatalf("create 2 NICs with same name %s", name)
done

2022-02-09 17:00 UTC, mgold1234 commented on client_nic_test.go
> +	if nic != nil {
done

2022-02-09 18:17 UTC, janosdebugs commented on client_nic_test.go
> +func assertCannotCreateNICWithSameNameDiffNetwork(
We could do that, however, we are trying to keep the assert functions reusable in other test cases. The naming should convey what the assert functions are doing rather than the current use case so future contributors feel that they can safely reuse the assert function. If  the assert function alone does not convey the logic in the test case using the assert function we can always add comments explaining what's happening.

2022-02-10 10:14 UTC, mgold1234 commented on client_nic_test.go
> +func assertCannotCreateNICWithSameNameDiffNetwork(
NP

2022-02-10 10:19 UTC, mgold1234 commented on client_nic_test.go
> +func assertCannotCreateNICWithSameName(
WDYT about -("create 2 NICs with same name %s (%v)", name, err)

2022-02-10 10:29 UTC, mgold1234 commented on client_nic_test.go
> +func assertCannotCreateNICWithSameName(
@janosdebugs , we have some functions for create nic:
1)  assertCanCreateNIC
2) assertCannotCreateNICWithSameName
3) assertCannotCreateNICWithVNICProfile
and more...

regarding 2 and 3 what do you suggest? if I change 2 as it was assertCannotCreateNIC, what is the differerent from 3?
maybe change it to 'assertCannotCreateNICWithName'? 
and 3 will be assertCannotCreateNICWithVNICProfile?

2022-02-10 10:57 UTC, mgold1234 commented on client_nic_create_test.go
> +	DiffVNICProfile, _ := assertCanFindDiffVNICProfile(helper, helper.GetVNICProfileID())
@janosdebugs , so I will change the function to catch the case that if there is no secondary profile then we will check the assertCannotCreateNICWithSameName and if we have more then 1 profile we will check this -assertCannotCreateNICWithVNICProfile.
WDYT?

2022-02-10 10:59 UTC, janosdebugs commented on client_nic_create_test.go
> +	DiffVNICProfile, _ := assertCanFindDiffVNICProfile(helper, helper.GetVNICProfileID())
Yes. Ideally, we'll skip the test if there is no secondary profile available. Later we can create a secondary profile to test.

2022-02-14 10:26 UTC, janosdebugs requested changes
Hey @mgold1234 thank you very much for your extensive work on this PR. There are several things to look at. The main points:

- Assert functions in this code base should use `t.Fatalf` to fail or `t.Skipf` to skip a test. We skip tests if the preconditions are not met (e.g. a second network is not available), while we fail a test when an actual error happened (e.g. the engine didn't respond).
- In Go please always check the returned `error` type instead of the return value. This makes the code more readable and less likely to introduce bugs.
- It seems the mock implementation does not correctly implement the rules, it will fail if there is any name conflict. Since the test passes it means that there is at least one test missing. There should be a failing test on the current implementation. This test should check that you *can* create two NICs with the same name on different VNIC profiles or different networks (depending on your investigation).

Since we don't know what the rules are, depending on your investigation of the naming conflict you need to implement *one* of the following two cases with 3 tests:

If the naming conflict applies to VNIC profiles:

- I cannot create two NICs with the same name on the VNIC profile.
- I can create two NICs with the same name on a different VNIC profile but the same network.
- I can create two NICs with the same name on different networks.

If the naming conflict applies to networks:

- I cannot create two NICs with the same name on the VNIC profile (which ever applies).
- I cannot create two NICs with the same name on a different VNIC profile but the same network.
- I can create two NICs with the same name on different networks.

2022-02-14 10:26 UTC, janosdebugs commented on client_nic_create_test.go
> +	DiffVNICProfileDiffNetwork, _ := assertCanFindDiffVNICProfileDiffNetwork(helper, helper.GetVNICProfileID())
In general, please use the error return and don't ignore that parameter. In this case, however, `t.Skipf` should be used in the assert function.

In Go, error checking should always rely on the returned `error` parameter to make the code more readable and less error-prone.

2022-02-14 10:26 UTC, janosdebugs commented on client_nic_create_test.go
> +	if DiffVNICProfileDiffNetwork == "" {
This condition should not be in this test case. If we don't find a second network we can use we should simply skip the test, not try to do something else.

2022-02-14 10:26 UTC, janosdebugs commented on client_nic_create_test.go
> +	assertCanRemoveNIC(t, nic1)
Removing the NIC is not necessary. When the VM is deleted at the end of the test the NIC is automatically destroyed.

2022-02-14 10:26 UTC, janosdebugs commented on client_nic_create_test.go
> +	DiffVNICProfileSameNetwork, _ := assertCanFindDiffVNICProfileSameNetwork(t, helper, helper.GetVNICProfileID())
Please make variables lower case. Only exported variables made available to other packages should start with an uppercase letter.

2022-02-14 10:26 UTC, janosdebugs commented on client_vnicprofile_test.go
> +		return "", fmt.Errorf("failed to list VNIC profiles (%w)", err)
Please use `t.Fatalf`.

2022-02-14 10:26 UTC, janosdebugs commented on client_vnicprofile_test.go
> +	return "", fmt.Errorf(
In this case we should use `t.Skipf` since the conditions required by the test are not met so we can't perform the test.

2022-02-14 10:26 UTC, janosdebugs commented on client_vnicprofile_test.go
> +		return "", fmt.Errorf("failed to verify VNIC profile ID %s", vnicProfileID)
Please use `t.Fatalf` in assert functions to make using them easier.

2022-02-14 10:26 UTC, janosdebugs commented on client_vnicprofile_test.go
> +	return "", fmt.Errorf(
Here we may use `t.Skipf` to make sure we skip the test if the preconditions are not met.

2022-02-14 10:26 UTC, janosdebugs commented on mock_nic_create.go
>  		if n.name == name {
This does not seem to implement the naming rules accurately. It will fail on all name conflicts, not just when it's the same network/vnic profile ID. If the tests pass on the mock then the tests are not working correctly.

2022-02-16 06:43 UTC, janosdebugs requested changes
Hey @mgold1234 as indicated in the previous review, the test needs to fail if the correct implementation is removed. This is not the case, when removing the latest change the test still passes. Please add a test that tests this case.

2022-02-16 06:43 UTC, janosdebugs commented on mock_nic_create.go
> +		if n.name == name && m.vnicProfiles[n.vnicProfileID].networkID == m.vnicProfiles[vnicProfileID].networkID {
I checked in my local setup, if I remove this change the test still passes. That means that there is no test that catches this bug.

2022-02-16 13:38 UTC, mgold1234 commented
@janosdebugs , there is an option that I can see the result of run here, before you do the review? 
there is a way to skip on workflows awaiting approval and the test will run ?

2022-02-16 14:38 UTC, janosdebugs commented
> @janosdebugs , there is an option that I can see the result of run here, before you do the review? there is a way to skip on workflows awaiting approval and the test will run ?

Yes, you can run the tests locally (the CI does the same) as described in the [contribution guidelines](https://github.com/oVirt/go-ovirt-client/blob/main/CONTRIBUTING.md).

2022-02-22 20:55 UTC, janosdebugs requested changes

2022-02-22 20:55 UTC, janosdebugs commented on mock_nic_create.go
> +		if n.name == name && m.vnicProfiles[n.vnicProfileID].networkID == m.vnicProfiles[vnicProfileID].networkID {
@mgold1234 this is still not resolved. If I remove this change and run the test suite the test passes. There needs to be a test that fails if this change is not added.

2022-02-22 21:14 UTC, mgold1234 commented
@janosdebugs I looked on this example test that also implement negative test:
func TestDiskAttachmentCannotBeAttachedToSecondVM(t *testing.T) {
	t.Parallel()
	helper := getHelper(t)

	vm1 := assertCanCreateVM(
		t,
		helper,
		fmt.Sprintf("disk_attachment_test_%s", helper.GenerateRandomID(5)),
		ovirtclient.CreateVMParams(),
	)
	vm2 := assertCanCreateVM(
		t,
		helper,
		fmt.Sprintf("disk_attachment_test_%s", helper.GenerateRandomID(5)),
		ovirtclient.CreateVMParams(),
	)
	disk := assertCanCreateDisk(t, helper)
	_ = assertCanAttachDisk(t, vm1, disk)
	assertCannotAttachDisk(t, vm2, disk, ovirtclient.EConflict)


this test is not failure, and only catch the specfic error that appear in this case.
I implement the same idea.

2022-02-22 21:18 UTC, janosdebugs commented
@mgold1234 please remove the implementation highlighted above and run the test suite. It must fail.

2022-02-23 12:07 UTC, janosdebugs commented
@mgold1234 as discussed, we don't have capacity to pursue this edge case further at this time. Closing this PR to revisit #82 after the current release cycle.

2022-02-23 12:07 UTC, closed without merging