Logging
oVirt/go-ovirt-client pull request #12
Opened 2021-07-15 20:41 UTC by janosdebugs

## Please describe the change you are making

This PR adds logging to the image upload process.

2021-07-19 09:36 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +	cli *oVirtClient
Not related to loging

2021-07-19 09:36 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +		optionsReq, err := http.NewRequest(http.MethodOptions, parsedTransferURL.String(), strings.NewReader(""))
Seems more like  a bug fix then logging

2021-07-19 09:38 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +		u.logger.Debugf(fmt.Sprintf("%s", err))
shouldn't that be err.string()
https://github.com/oVirt/go-ovirt-client/blob/main/errors.go#L97-L98

2021-07-19 09:39 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +}
Not related to logging

2021-07-19 09:39 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
>  			}
Seems more like a bug fix then logging

2021-07-19 09:42 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +	transferService := imageTransfersService.ImageTransferService(transferID)
Not related to logging

2021-07-19 09:46 UTC, Gal-Zaidman requested changes
PR looks good, I think that we will probably add more logs as we will refactor the code.
But there is a large part of this PR that is not related to logging, its more of a refactor/bugfix change.
I think we should split this into 2 PRs or at least 2 commits (and not squash merge)

2021-07-19 16:10 UTC, janosdebugs commented
Thanks @Gal-Zaidman the issues should now be resolved.

2021-07-21 07:35 UTC, Gal-Zaidman commented
> Thanks @Gal-Zaidman the issues should now be resolved.

I still see that everything is the same

2021-07-21 08:27 UTC, Gal-Zaidman approved these changes

2021-07-21 08:28 UTC, merged