adding Memory methods (#138)
oVirt/go-ovirt-client pull request #140
Opened 2022-03-31 15:38 UTC by eslutsky

2022-04-01 07:33 UTC, janosdebugs requested changes
Looks good, a few changes, and the mocks are still missing.

2022-04-01 07:33 UTC, janosdebugs commented on client_vm_create.go
> +	//panic(newError(EBug, "Failed to build 'hugepages' custom property from value %d", params.Memory()))
Please don't commit commented-out code.

2022-04-01 07:33 UTC, janosdebugs commented on client_vm.go
> +	memory         int64
Shouldn't this be `*int64` so you can indicate a `nil` value? That would help with determining if the memory has been set or not.

2022-04-01 07:33 UTC, janosdebugs commented on client_vm_test.go
> +	for name, param := range params {
Please keep the tests simple and  readable, I don't think we need the fancy data-driven logic here.

2022-04-04 08:14 UTC, eslutsky commented on client_vm_create.go
> +	//panic(newError(EBug, "Failed to build 'hugepages' custom property from value %d", params.Memory()))
fixed

2022-04-04 08:14 UTC, eslutsky commented on client_vm.go
> +	memory         int64
fixed

2022-04-04 08:14 UTC, eslutsky commented on client_vm_test.go
> +	for name, param := range params {
fixed

2022-04-04 08:24 UTC, janosdebugs requested changes

2022-04-04 08:24 UTC, janosdebugs commented on client_vm.go
> +	memory         *int64
Why is this a pointer? It seems to me that the API always returns the memory field.

2022-04-04 08:24 UTC, janosdebugs commented on mock_vm_create.go
> +		memory:         params.Memory(),
Please handle the case when this is not set. What is the default?

2022-04-04 08:24 UTC, janosdebugs commented on client_vm_test.go
> +func TestVMCreationWithMemory(t *testing.T) {
Please add a test that checks the default behavior if the memory is not set. How much memory is allocated by default?

2022-04-04 09:48 UTC, eslutsky commented on client_vm.go
> +	memory         *int64
Fixed

2022-04-04 09:48 UTC, eslutsky commented on mock_vm_create.go
> +		memory:         params.Memory(),
Fixed

2022-04-04 09:48 UTC, eslutsky commented on client_vm_test.go
> +func TestVMCreationWithMemory(t *testing.T) {
Fixed

2022-04-04 09:55 UTC, janosdebugs approved these changes

2022-04-04 09:55 UTC, janosdebugs commented on mock_vm_create.go
> +	memory := int64(1073741824)
Is this the same default as in the oVirt engine?

2022-04-04 09:56 UTC, eslutsky commented on mock_vm_create.go
> +	memory := int64(1073741824)
yes

2022-04-04 11:53 UTC, merged