Added TLS provider
oVirt/go-ovirt-client pull request #20
Opened 2021-08-09 11:58 UTC by janosdebugs

This change adds a generic provider interface that has the ability to return a TLS configuration. This change is dependent on https://github.com/oVirt/ovirt-engine-sdk-go/pull/235

It is required for the implementation of #7.

2021-08-10 08:10 UTC, Gal-Zaidman commented on README.md
> +    tlsProvider = ovirtclient.CACertsFromFile("/path/to/cert.pem")
I think you need to make it clear that it is one of them, it is a readme it needs to be friendly.
Something like:
```
Create a TLS provider and load certificates, this can be done by:
// Using system roots certificates
tlsProvider := ovirtclient.CACertsFromSystem()
// Using a certificate in PEM formant which from a variable
tlsProvider = ovirtclient.CACertsFromMemory(certInPemFormat)
// Using all certificates from a directory
tlsProvider = ovirtclient.CACertsFromDir("/path/to/certs")
// Using a cert file path
tlsProvider = ovirtclient.CACertsFromFile("/path/to/cert.pem")
```

Feel free to rephrase it is just an example :)

2021-08-10 08:28 UTC, Gal-Zaidman commented on tls.go
> +			if strings.HasPrefix(path2.Base(filepath.ToSlash(fullPath)), ".") {
why is it a problem to load certs which begin with '.'?
Is there some limitation to hidden files?

2021-08-10 08:37 UTC, Gal-Zaidman commented on tls.go
> +}
This way you can only use one of them, but maybe a user will want to reference a dir and a file or something like that? do you think this is a valid use case? if so you may want to change the pattern to extend `standardTLSProvider` all your functions for adding certs already supports it so it will not be a big change...
Something like ```WithCACertsFromDir... ```

2021-08-10 08:37 UTC, Gal-Zaidman requested changes
Very small changes and questions,
Looks good

2021-08-10 10:59 UTC, janosdebugs commented on tls.go
> +			if strings.HasPrefix(path2.Base(filepath.ToSlash(fullPath)), ".") {
Sometimes package management software place dot files in folders they manage. It would be unfortunate to try and load them.

2021-08-11 19:53 UTC, janosdebugs commented on tls.go
> +}
Completely overhauled, please take a look.

2021-08-11 20:03 UTC, janosdebugs commented on tls.go
> +			if strings.HasPrefix(path2.Base(filepath.ToSlash(fullPath)), ".") {
Overhauled this, now it allows specifying regular expressions what files to load.

2021-08-16 08:40 UTC, Gal-Zaidman approved these changes

2021-08-16 08:40 UTC, merged