Fix VM getters to work with shutdown VMs
oVirt/go-ovirt-client pull request #257
Opened 2024-10-23 18:56 UTC by aravindhp

## Please describe the change you are making
convertSDKNicConfiguration() was assuming that VMs will have an active NIC configuration. This is not the case for shutdown VMs, so we need to account for that.

## Are you the owner of the code you are sending in, or do you have permission of the owner?

I am not the owner

## The code will be published under the BSD 3 clause license. Have you read and understood this license?

Yes

2026-02-03 12:24 UTC, dupondje requested changes

2026-02-03 12:24 UTC, dupondje commented on vm.go
> -			Address: ipv4.MustAddress(),
We can just replace this here with ipv4.Address() ?
No need to introduce a new variable?

2026-02-03 12:24 UTC, dupondje commented on vm.go
> +	if !ok {
This will break vm's with IPv6. Cause it's not because ipv4 is not found, that there is no IPv6.
I think? we can just return null if ipv4 and ipv6 is not found?

2026-02-10 00:21 UTC, aravindhp reviewed
Thank you for the review, @dupondje

2026-02-10 00:21 UTC, aravindhp commented on vm.go
> -			Address: ipv4.MustAddress(),
How do I do that given `ipv4.Address()` returns two values?

2026-02-10 00:21 UTC, aravindhp commented on vm.go
> +	if !ok {
I have addressed this. Please review again.

2026-02-10 14:29 UTC, dupondje requested changes
Looks good already. Some minor changes and we're done :)

2026-02-10 14:29 UTC, dupondje commented on vm.go
> +			nicConfiguration = NewNicConfiguration(
I would add this on top of the function.
And then for IPv4 do nicConfiguration.WithIP(...)

2026-02-10 14:29 UTC, dupondje commented on vm.go
> +	var nicConfiguration BuildableNicConfiguration
Initialize a new one here

2026-02-10 14:29 UTC, dupondje commented on vm.go
> +		nicConfiguration = NewNicConfiguration(
nicConfigration.WithIP() here

2026-02-12 00:10 UTC, aravindhp reviewed
@dupondje I pushed another round of changes. Please review again and thank you for your patience.

2026-02-12 00:10 UTC, aravindhp commented on vm.go
> +		return nil
I am not sure if I should be returning `nil` here or just remove this if block which will result in `nicConfiguration` being returned.

2026-06-04 08:49 UTC, dupondje commented on vm.go
> +		return nil
nil is fine.

2026-06-04 08:50 UTC, dupondje approved these changes

2026-06-04 08:50 UTC, merged