Better error messages / error codes
oVirt/go-ovirt-client pull request #5
Opened 2021-07-13 08:01 UTC by janosdebugs

## Please describe the change you are making

This PR adds better error messages and error codes to identify failures from the oVirt engine.

2021-07-14 06:59 UTC, janosdebugs commented
Blocked by ovirt/ovirt-engine-sdk-go#227.

2021-07-15 09:16 UTC, janosdebugs commented
@Gal-Zaidman here's another one for review please.

2021-07-15 10:18 UTC, Gal-Zaidman commented on errors.go
> +func (e ErrorCode) IsPermanent() bool {
Need to change to "CanAutoRetry"

2021-07-15 10:25 UTC, Gal-Zaidman commented on errors.go
> +	case EPending:
Please remove it from the list since a pending error can be retried

2021-07-15 10:43 UTC, Gal-Zaidman commented on errors.go
> +	Is(ErrorCode) bool
Rename please since it is confusing with errors.Is

2021-07-15 10:47 UTC, Gal-Zaidman commented on errors.go
> +func newError(code ErrorCode, message string, args ...interface{}) EngineError {
please rename "message" to "format".
See https://pkg.go.dev/fmt#Errorf

2021-07-15 10:54 UTC, Gal-Zaidman commented on errors.go
> +func wrap(err error, code ErrorCode, message string, args ...interface{}) EngineError {
please rename "message" to "format".
See https://pkg.go.dev/fmt#Errorf

2021-07-15 10:59 UTC, Gal-Zaidman commented on errors.go
> +	copy(realArgs[0:len(args)], args)
Why not just:
```
realArgs := append(args, err)
```
?

2021-07-15 11:05 UTC, Gal-Zaidman commented on errors.go
> +	realMessage := fmt.Sprintf(fmt.Sprintf("%s %s", message, "(%v)"), realArgs...)
I think you can replace the nested fmt with:
```
	realMessage := fmt.Sprintf("%s (%%v)", message, realArgs...)
```

2021-07-15 11:09 UTC, Gal-Zaidman commented on errors.go
> +		return wrap(err, EAccessDenied, "access denied, check your credentials")
or user is locked

2021-07-15 12:20 UTC, Gal-Zaidman commented on client_cluster_list.go
> +		return nil, nil
On get you returned an error no found when there was nothing and here you are returning nil, is it because it is List?
I think you need to document that nil will be return if nothing is found

2021-07-15 12:22 UTC, Gal-Zaidman commented on client_disk_list.go
> +		return nil, nil
same as above, and I guess same for every list op

2021-07-15 12:24 UTC, Gal-Zaidman commented on client_disk_remove.go
> +			EUnidentified,
Not sure that EUnidentified is the correct error here, 
It can be that the disk ID is wrong and disk doesn't exist
maybe do a get before remove, its one more API call but it will verify that...
or
maybe we can try and understand the case from the error which is returned

2021-07-15 12:26 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +			EBug,
It can fail due to many reasons, not necessarily a bug

2021-07-15 12:31 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +			EUnidentified,
Not sure that EUnidentified is the correct error here, especially if we will give a proper error in the method itself

2021-07-15 12:36 UTC, Gal-Zaidman commented on client_host.go
>  func convertSDKHost(sdkHost *ovirtsdk4.Host) (Host, error) {
I see that you changed only the convertSDKHost but didn't touch any of the other convertSDK functions, why?

2021-07-15 12:39 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +		panic(wrap(err, EBug, "bug: failed to convert disk"))
There are times that we panic when convertSDK fails and there are times which we return an error here https://github.com/oVirt/go-ovirt-client/pull/5/files?file-filters%5B%5D=.go&file-filters%5B%5D=.mod#diff-af1929f7ad8f6cbb7ca3e031eff3dafa14e830d8f8d502513d56882ca6476309R17
I think we should be consistent

2021-07-15 12:41 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +		return wrap(err, EUnidentified, "failed to finalize image upload")
Same as above, this is not necessarily unidentified oVirt error

2021-07-15 12:46 UTC, Gal-Zaidman commented on client_storagedomain_get.go
> +		return nil, wrap(err, EUnidentified, "failed to convert storage domain")
What will be printed in this case?
Will the wrapped Field missing error be printed? because those are the errors it returns

2021-07-15 12:47 UTC, Gal-Zaidman commented on client_storagedomain_list.go
> +			return nil, wrap(err, EBug, "failed to convert storage domain %d in listing", i)
Above it was EUnidentified, here it is a bug... any reason for the change?

2021-07-15 12:48 UTC, janosdebugs commented on client_disk_remove.go
> +			EUnidentified,
EUnidentified is an error type that will cause wrap to engage pattern matching for the error message.

2021-07-15 12:48 UTC, Gal-Zaidman commented on client_template.go
>  	if !ok {
I think you missed this one

2021-07-15 12:49 UTC, Gal-Zaidman commented on client_template_list.go
> +		return nil, newError(ENotFound, "host list response didn't contain hosts")
On the others you returned nil, nil with no error

2021-07-15 12:50 UTC, janosdebugs commented on client_disk_uploadimage.go
> +			EBug,
The createDiskForUpload does not interact with the engine, it simply calls SDK functions to build an object to pass to the SDK. If an error is returned it means that there i sa bug.

2021-07-15 12:51 UTC, janosdebugs commented on client_disk_uploadimage.go
> +		panic(wrap(err, EBug, "bug: failed to convert disk"))
You are correct, we should return this one. The panic was added for sure fire bugs before we had error codes.

2021-07-15 12:52 UTC, janosdebugs commented on client_cluster_list.go
> +		return nil, nil
I'll replace it with an empty slice.

2021-07-15 13:13 UTC, janosdebugs commented on client_storagedomain_get.go
> +		return nil, wrap(err, EUnidentified, "failed to convert storage domain")
Yes, the wrap function prints the wrapped error message too.

2021-07-15 13:13 UTC, janosdebugs commented on client_storagedomain_list.go
> +			return nil, wrap(err, EBug, "failed to convert storage domain %d in listing", i)
Yes, converting SDK objects should always succeed. We should anticipate what fields are returned and handle them accordingly.

2021-07-15 13:16 UTC, janosdebugs commented on errors.go
> +	realMessage := fmt.Sprintf(fmt.Sprintf("%s %s", message, "(%v)"), realArgs...)
Can't do that, the format/message can contain multiple replacement sequences.

2021-07-15 13:16 UTC, janosdebugs commented on errors.go
> +		return wrap(err, EAccessDenied, "access denied, check your credentials")
We have to test how the engine reacts in that case.

2021-07-15 19:02 UTC, janosdebugs commented on client_disk_uploadimage.go
> +		panic(wrap(err, EBug, "bug: failed to convert disk"))
Update: in this specific case the function doesn't return an error, and it shouldn't since errors only happen when a bug happens.

2021-07-18 09:12 UTC, Gal-Zaidman commented on client_storagedomain_get.go
> +		return nil, wrap(err, EUnidentified, "failed to convert storage domain")
OK, regarding the resolved comment in storagedomain_list.
Here you returned a EUnidentified error and not EBug like in most places.
So I think either have a good reason or be consistant

2021-07-18 09:20 UTC, Gal-Zaidman commented on client_disk_remove.go
> +			EUnidentified,
OK thanks, it make sense to me now :)

2021-07-18 09:23 UTC, Gal-Zaidman commented on client_disk_remove.go
> +		case <-time.After(10 * time.Second):
I see that the timeouts here are different on each retry method.
Maybe we should give the user a way to configure that with With.Context[1], and set a default.
I just think it is confusing that each retry method has a different interval (it also make sense because you don't want to retry connection like disk removal)

[1] https://pkg.go.dev/context#example-WithValue

2021-07-18 09:24 UTC, Gal-Zaidman commented on client_disk_remove.go
> +		case <-time.After(10 * time.Second):
I see that the timeouts here are different on each retry method.
Maybe we should give the user a way to configure that with With.Context[1], and set a default.
I just think it is confusing that each retry method has a different interval (it also make sense because you don't want to retry connection like disk removal)

[1] https://pkg.go.dev/context#example-WithValue

2021-07-18 09:35 UTC, Gal-Zaidman commented on client_disk_uploadimage.go
> +		panic(wrap(err, EBug, "bug: failed to convert disk"))
So why are you not changing it to return an error?

2021-07-18 09:41 UTC, Gal-Zaidman commented on client_template_get.go
> +		return nil, wrap(err, EUnidentified, "failed to convert template object")
Same as above, should probably be EBug

2021-07-18 09:45 UTC, Gal-Zaidman commented on client_util.go
> +// waitForJobFinished waits for a job to truly finish. This is especially important when disks are involved as their status changes to OK prematurely.
I think you can remove "This is especially important when disks are involved as their status changes to OK prematurely." or at least say "Note: This is especially important when disks are involved as their status changes to OK prematurely."
Since it doesn't describe the function, just the motivation for creating/using it

2021-07-18 09:53 UTC, Gal-Zaidman commented on client_util.go
> +// waitForJobFinished waits for a job to truly finish. This is especially important when disks are involved as their status changes to OK prematurely.
Also maybe add an example of how to set a correlationID, since it is not trivial, something like:
```
// waitForJobFinished waits for a job to truly finish by checking it was removed from the oVirt job queue using a caller predefined job correlationID.
// correlationID is a quarry parameter assigned to a job before it is sent to the ovirt engine, it must be unique.
// To set a correlationID add `Query("correlation_id", correlationID)` to the engine API call, for example:
correlationID := fmt.Sprintf("image_transfer_%s", utilrand.String(5))
conn.SystemService().DisksService().DiskService(diskId).
		Update().
		Query("correlation_id", correlationID).
		Send()
```

2021-07-18 10:02 UTC, Gal-Zaidman commented on client_vm.go
>  func NewVMCPUTopo(cores uint, threads uint, sockets uint) (VMCPUTopo, error) {
Why are you panic in https://github.com/oVirt/go-ovirt-client/pull/5/files#diff-c9e88235f1f664443d76481488dac388b8a048485d63e1c41d244add41d5940aR41

I think an error should be returned

2021-07-18 10:10 UTC, Gal-Zaidman commented on errors.go
> +		return wrap(err, EAccessDenied, "access denied, check your credentials")
Do you want to track it as an issue?

2021-07-18 10:12 UTC, Gal-Zaidman requested changes
- Some very minor changes are required.
- Wanted to ask you to implement a general retry function since it has the same structure everywhere, but I see you beat me to the punch https://github.com/oVirt/go-ovirt-client/pull/14

2021-07-18 11:13 UTC, janosdebugs commented on errors.go
> +		return wrap(err, EAccessDenied, "access denied, check your credentials")
#15

2021-07-18 11:13 UTC, janosdebugs commented on client_disk_remove.go
> +		case <-time.After(10 * time.Second):
@Gal-Zaidman leave it for now, this is handled properly in #14

2021-07-18 11:14 UTC, janosdebugs commented on client_template_get.go
> +		return nil, wrap(err, EUnidentified, "failed to convert template object")
Fixed in #14

2021-07-18 11:16 UTC, janosdebugs commented on client_vm.go
>  func NewVMCPUTopo(cores uint, threads uint, sockets uint) (VMCPUTopo, error) {
I'm afraid this link is broken. Can you add the comment in the correct place?

2021-07-18 11:56 UTC, Gal-Zaidman approved these changes

2021-07-18 11:57 UTC, merged