introduce CopyDiskToStorageDomain method to ovirt-client
oVirt/go-ovirt-client pull request #51
Opened 2021-10-18 07:51 UTC by eslutsky

this method will allow copying disks between different storage domains.

2021-11-24 12:48 UTC, janosdebugs requested changes
Looks good, a few minor changes.

2021-11-24 12:48 UTC, janosdebugs commented on client_template_copy_disk.go
> +	o.logger.Infof("Starting copy template disk to different storage domain.")
This log message is not useful. Please include disk and storage domain IDs. Also note that `retry()` logs automatically, you don't need to add this message here.

2021-11-24 12:48 UTC, janosdebugs commented on mock_template_copy_disk.go
> +	c.client.disks[c.disk.ID()] = c.disk
Please add a general lock for `c.client` here to avoid race conditions.

2021-11-24 12:48 UTC, janosdebugs commented on mock_template_copy_disk.go
> +// Code generated automatically using go:generate. DO NOT EDIT.
Please remove this comment, this file is not auto-generated.

2021-11-24 12:48 UTC, janosdebugs commented on client_storagedomain.go
> +	if err := d.client.waitForJobFinished(d.correlationID, retries); err != nil {
We should wait for the disk to return to OK status here. That may happen somewhat after the job finished in <oVirt 4.4.7.

2021-11-29 13:35 UTC, eslutsky commented on client_template_copy_disk.go
> +	o.logger.Infof("Starting copy template disk to different storage domain.")
removed this log

2021-11-29 13:39 UTC, eslutsky commented on mock_template_copy_disk.go
> +// Code generated automatically using go:generate. DO NOT EDIT.
ok

2021-11-29 13:42 UTC, eslutsky commented on mock_template_copy_disk.go
> +	c.client.disks[c.disk.ID()] = c.disk
> 

beside the lock , the actual implementation is incorrect , we need to  append the storageDomainID to the disk, working on it

2021-11-30 10:41 UTC, eslutsky commented on client_storagedomain.go
> +	if err := d.client.waitForJobFinished(d.correlationID, retries); err != nil {
fixed to using WaitForDiskOk instead of  waitForJobFinished

2021-11-30 11:15 UTC, eslutsky commented on mock_template_copy_disk.go
> +	c.client.disks[c.disk.ID()] = c.disk
added lock and append

2021-11-30 11:32 UTC, eslutsky commented on mock_template_copy_disk.go
> +	c.client.disks[c.disk.ID()] = c.disk
removed lock :)

2021-11-30 11:52 UTC, janosdebugs requested changes
Apart from a few grammar fixes, please split waiting for the disk to be OK and waiting for a job to finish. The function names are misleading and the correlation ID workaround should never be exposed publicly.

2021-11-30 11:52 UTC, janosdebugs commented on client_disk.go
> +	WaitForDiskOk(diskID string, correlationID string, retries []RetryStrategy) error
Let's capitalize OK here as we do in other places too.

2021-11-30 11:52 UTC, janosdebugs commented on client_disk_helper_imagetransfer.go
> +func (i *imageTransferImpl) waitForTransferOk() (err error) {
OK is incorrectly written lowercase, please capitalize it.

2021-11-30 11:52 UTC, janosdebugs commented on client_disk_helper_imagetransfer.go
> -	if err := i.cli.waitForJobFinished(i.correlationID, i.retries); err != nil {
We need to wait for the job to be finished and then for the disk to become OK, otherwise it won't work on older oVirt versions.

2021-11-30 11:52 UTC, janosdebugs commented on client_disk_util.go
> +	if err := o.waitForJobFinished(correlationID, retries); err != nil {
If you call waitForJobFinished here then the name of the function is misleading.

2021-11-30 11:52 UTC, janosdebugs commented on client_disk_util.go
> +func (o *oVirtClient) WaitForDiskOk(diskID string, correlationID string, retries []RetryStrategy) (err error) {
The correlation ID should never be exposed publicly, it is an internal feature.

2021-11-30 11:52 UTC, janosdebugs commented on client_disk.go
> +	WaitForDiskOk(diskID string, correlationID string, retries []RetryStrategy) error
Also, WaitForDiskOK, as a public funcion, should never have the correlation ID because the correlation Id is an internal workaround and should not be used by anyone outside.

The retries should use the `...RetryStrategy` type.

2021-11-30 11:52 UTC, janosdebugs commented on client_storagedomain.go
> +	if err := d.client.WaitForDiskOk(diskID, d.correlationID, retries); err != nil {
Please split in two: waiting for the job to finish and the disk to be ok.

2021-11-30 12:57 UTC, eslutsky commented on client_disk_helper_imagetransfer.go
> +func (i *imageTransferImpl) waitForTransferOk() (err error) {
done

2021-11-30 13:07 UTC, eslutsky commented on client_disk.go
> +	WaitForDiskOk(diskID string, correlationID string, retries []RetryStrategy) error
we must have correlation ID in order to know the operation is completed. it appears that we cannot make this function public then

2021-11-30 14:02 UTC, eslutsky commented on client_disk.go
> +	WaitForDiskOk(diskID string, correlationID string, retries []RetryStrategy) error
removed correlelationID

2021-11-30 14:02 UTC, eslutsky commented on client_storagedomain.go
> +	if err := d.client.WaitForDiskOk(diskID, d.correlationID, retries); err != nil {
done

2021-11-30 14:03 UTC, eslutsky commented on client_disk_util.go
> +	if err := o.waitForJobFinished(correlationID, retries); err != nil {
removed this call

2021-11-30 14:03 UTC, janosdebugs requested changes

2021-11-30 14:03 UTC, janosdebugs commented on client_storagedomain.go
> +	if err := d.client.WaitForDiskOK(diskID, retries[0]); err != nil {
Why `retries[0]`? This should be `retries...`.

2021-11-30 14:47 UTC, eslutsky commented on client_disk_helper_imagetransfer.go
> -	if err := i.cli.waitForJobFinished(i.correlationID, i.retries); err != nil {
done

2021-11-30 14:51 UTC, eslutsky commented on client_storagedomain.go
> +	if err := d.client.WaitForDiskOK(diskID, retries[0]); err != nil {
changed to `retries...`

2021-12-01 12:48 UTC, janosdebugs commented on mock_disk_util.go
> +	adisk, ok := m.disks[diskID]
What is the purpose of calling it `adisk`? You can just remove the variable names from the return types above.

2021-12-02 08:05 UTC, eslutsky commented on mock_disk_util.go
> +	adisk, ok := m.disks[diskID]
okay done

2021-12-02 09:23 UTC, janosdebugs approved these changes
LGTM :)

2021-12-02 09:43 UTC, merged