introduce storage domain disks methods
oVirt/go-ovirt-client pull request #58
Opened 2021-10-21 13:37 UTC by eslutsky

## Please describe the change you are making
Introducing Storage domain methods for querying and removal disks.

2021-11-11 13:51 UTC, janosdebugs commented
@eslutsky please fix the formatting issues.

2021-11-15 09:42 UTC, eslutsky commented
> @eslutsky please fix the formatting issues.
rebased on your [formatting PR](https://github.com/oVirt/go-ovirt-client/pull/66)

2021-11-15 20:14 UTC, janosdebugs requested changes
A few things to take care of, otherwise looks good.

2021-11-15 20:14 UTC, janosdebugs commented on client_storagedomain_test.go
> +func TestStorageDomainDiskGet(t *testing.T) {
This test seems to be a copied version of `TestDiskCreationAndUpdate`. It would be good to use assert functions, such as `assertCanCreateDisk` to make the test shorter and more readable.

2021-11-15 20:14 UTC, janosdebugs commented on mock_storagedomain_get_disk.go
> +		return item, nil
Please add a check if the ID of the disk matches the storage domain ID and only return if the storage domain ID matches.

2021-11-15 20:14 UTC, janosdebugs commented on client_storagedomain.go
> +	RemoveStorageDomainDisk(id string, diskID string, retries ...RetryStrategy) error
Why do we need this function? What's wrong with simply removing the disk? Do we need it somewhere?

2021-11-16 08:18 UTC, eslutsky commented on client_storagedomain.go
> +	RemoveStorageDomainDisk(id string, diskID string, retries ...RetryStrategy) error
well, when we do the normal disk removal we provide it with a diskID ONLY,  we need to cover cases this disk belongs to a template so we also need the SD id (the same disk id can be on a few SDs).

2021-11-16 08:28 UTC, janosdebugs commented on client_storagedomain.go
> +	RemoveStorageDomainDisk(id string, diskID string, retries ...RetryStrategy) error
In this case it would be better to call the function `RemoveDiskFromStorageDomain`.

2021-11-16 08:30 UTC, janosdebugs commented on client_storagedomain.go
> +	RemoveStorageDomainDisk(id string, diskID string, retries ...RetryStrategy) error
We also need to investigate how this behavior works exactly, otherwise we can't model it in go-ovirt-client.

2021-11-17 09:56 UTC, eslutsky commented on client_storagedomain.go
> +	RemoveStorageDomainDisk(id string, diskID string, retries ...RetryStrategy) error
so also change the getter to GetDiskFromStorageDomain ?

2021-11-17 09:59 UTC, eslutsky commented on client_storagedomain_test.go
> +func TestStorageDomainDiskGet(t *testing.T) {
we have  this assert function https://github.com/oVirt/go-ovirt-client/blob/d0eb65c6633dd76c231753795b354ae42fb09802/client_disk_attachment_test.go#L47
but  we might need to add it  OptionalDiskParameters

2021-11-17 10:21 UTC, janosdebugs commented on client_storagedomain.go
> +	RemoveStorageDomainDisk(id string, diskID string, retries ...RetryStrategy) error
Probably yes.

2021-11-17 10:22 UTC, janosdebugs commented on client_storagedomain_test.go
> +func TestStorageDomainDiskGet(t *testing.T) {
Feel free to, as long as the optional disk params can be set to nil

2021-11-18 14:32 UTC, eslutsky commented on client_storagedomain.go
> +	RemoveStorageDomainDisk(id string, diskID string, retries ...RetryStrategy) error
done

2021-11-18 14:35 UTC, eslutsky commented on client_storagedomain_test.go
> +func TestStorageDomainDiskGet(t *testing.T) {
I've used the existing  assertCanCreateDisk function from the attachment_test

2021-11-18 15:50 UTC, janosdebugs requested changes
One change required please.

2021-11-18 15:50 UTC, janosdebugs commented on mock_storagedomain_remove_disk.go
> +	if _, ok := m.disks[diskID]; ok {
This implementation is incorrect, the storage domain must be removed from the disk, or if no storage domains are left, the disk must be removed.

2021-11-22 11:58 UTC, eslutsky commented on mock_storagedomain_remove_disk.go
> +	if _, ok := m.disks[diskID]; ok {
this code doesn't really delete anything :) , just made it as place holder to fix later :)

2021-11-22 12:34 UTC, eslutsky commented on mock_storagedomain_remove_disk.go
> +	if _, ok := m.disks[diskID]; ok {
since the storageDomainIDs is defined as slice:
https://github.com/oVirt/go-ovirt-client/blob/891a509748e931662b950513b06a683b6b721e8e/client_disk.go#L697

it's not very removal friendly , we can try use this method https://github.com/golang/go/wiki/SliceTricks#delete 
but it seems hacky.

2021-11-22 12:40 UTC, janosdebugs commented on mock_storagedomain_remove_disk.go
> +	if _, ok := m.disks[diskID]; ok {
Either that, or you can change it to a map by ID.

2021-11-22 12:43 UTC, eslutsky commented on mock_storagedomain_remove_disk.go
> +	if _, ok := m.disks[diskID]; ok {
yea changing to map by ID is a much cleaner solution

2021-11-22 12:44 UTC, janosdebugs commented on mock_storagedomain_remove_disk.go
> +	if _, ok := m.disks[diskID]; ok {
Do you want to do it?

2021-11-22 12:45 UTC, eslutsky commented on mock_storagedomain_remove_disk.go
> +	if _, ok := m.disks[diskID]; ok {
okay , i'll add  commit for it

2021-11-22 14:38 UTC, eslutsky commented on mock_storagedomain_remove_disk.go
> +	if _, ok := m.disks[diskID]; ok {
as our off-thread conversation, we want to preserve the StorageDomains Order so we would like to keep it a slice.

2021-11-22 14:39 UTC, eslutsky commented on mock_storagedomain_remove_disk.go
> +	if _, ok := m.disks[diskID]; ok {
implemented it as slice removal by ID.

2021-11-22 16:08 UTC, janosdebugs requested changes
Hey @eslutsky a few minor changes. :)

2021-11-22 16:08 UTC, janosdebugs commented on client_storagedomain.go
> +	// GetStorageDomainDisk return a single disk from the storage domain or an error if a disk cannot be found
Suggested comment:

```go
// GetStorageDomainDisk returns a single disk from a specific storage domain, or an error if no disk can be found.
```

2021-11-22 16:08 UTC, janosdebugs commented on client_storagedomain_test.go
> +	err := client.RemoveDiskFromStorageDomain(helper.GetSecondaryStorageDomainID(t), disk.ID())
This removal will never work since the disk is always created on the primary storage domain. We need a better test here, but we can add it later when you implement the clone disk feature.

2021-11-22 16:14 UTC, eslutsky commented on client_storagedomain.go
> +	// GetStorageDomainDisk return a single disk from the storage domain or an error if a disk cannot be found
done

2021-11-22 16:15 UTC, eslutsky commented on client_storagedomain_test.go
> +	err := client.RemoveDiskFromStorageDomain(helper.GetSecondaryStorageDomainID(t), disk.ID())
agreed removed the tests for now , re-add them with the clone PR

2021-11-22 16:17 UTC, eslutsky commented on client_storagedomain.go
> +	// RemoveStorageDomainDisk removes Disk from the storageDomain
done

2021-11-22 16:28 UTC, janosdebugs approved these changes

2021-11-22 16:28 UTC, merged