introduce tags support to VMs
oVirt/go-ovirt-client pull request #97
Opened 2021-12-07 15:52 UTC by eslutsky

## Please describe the change you are making
introduce tags support for vms

2021-12-13 11:42 UTC, janosdebugs requested changes
A few small changes please.

2021-12-13 11:42 UTC, janosdebugs commented on client_tag_create.go
> +// Code generated automatically using go:generate. DO NOT EDIT.
This code is not auto-generated, please remove this line to avoid confusion.

2021-12-13 11:42 UTC, janosdebugs commented on client_tag.go
> +	// GetTag returns a single network based on its ID.
Description is incorrect.

2021-12-13 11:42 UTC, janosdebugs commented on mock_tag_create.go
> +func (m *mockClient) createTag(
What is the purpose of this separate function?

2021-12-13 11:42 UTC, janosdebugs commented on mock_tag_remove.go
> +	delete(m.tags, id)
The tags need to be removed from the VMs too in this case.

2021-12-13 11:42 UTC, janosdebugs commented on client_vm_add_tag.go
> +func (o *oVirtClient) AddTagToVM(id string, tagID string, retries ...RetryStrategy) (err error) {
Please add a convenience function to the VM object to call this function.

2021-12-13 13:21 UTC, eslutsky commented on client_vm.go
> +func (v *vm) Tags(retries ...RetryStrategy) ([]Tag, error) {
done

2021-12-13 13:21 UTC, eslutsky commented on client_vm_add_tag.go
> +func (o *oVirtClient) AddTagToVM(id string, tagID string, retries ...RetryStrategy) (err error) {
done

2021-12-13 13:21 UTC, eslutsky commented on mock_tag_remove.go
> +	delete(m.tags, id)
done

2021-12-13 13:22 UTC, eslutsky commented on client_tag_create.go
> +// Code generated automatically using go:generate. DO NOT EDIT.
done

2021-12-13 13:22 UTC, eslutsky commented on mock_tag_create.go
> +func (m *mockClient) createTag(
removed

2021-12-13 13:25 UTC, janosdebugs approved these changes
LGTM

2021-12-13 16:03 UTC, janosdebugs commented
@eslutsky you are good to go, just rebase and merge.

2021-12-13 16:03 UTC, janosdebugs approved these changes

2021-12-14 08:49 UTC, janosdebugs approved these changes

2021-12-14 09:23 UTC, merged